#! /bin/sh

# https://www.reddit.com/r/bspwm/comments/jqving/sxhkd_bind_keys_depending_on_keyboard_layout/
sxhkd -m1&

#bspc monitor -d I II III IV V VI VII VIII IX X

#bspc config border_width         2
bspc config border_width         3
#bspc config window_gap          12
bspc config window_gap          5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# https://www.reddit.com/r/unixporn/comments/3mj8nn/setting_bspwm_to_floating/
bspc rule -a yad-calendar state=floating
# $ xprop -name Calendar
bspc rule -a Calendar follow=off state=floating
## bspc rule -a gnome-calendar follow=off state=floating

# joao

# my rules
bspc rule -a nautilus desktop='^6'
bspc rule -a msedge desktop='^7'
bspc rule -a firefox desktop='^8'

# https://protesilaos.com/codelog/multihead-bspwm-polybar/
my_laptop_external_monitor=$(xrandr | grep 'HDMI-1 connected' | awk '{print $2}')
if [ "$my_laptop_external_monitor" = "connected" ]; then
	xrandr --output eDP-1 --auto --pos 0x0 --output HDMI-1 --pos 1366x-450 --primary

	bspc monitor eDP-1 -d I
	bspc monitor HDMI-1 -d II III IV V VI VII VIII IX X

	# Terminate already running bar instances
	killall -q polybar
	
	# Wait until the processes have been shut down
	while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
	#polybar laptop_aux &
	polybar laptop_external &
else
	#xrandr --output eDP-1 --auto --primary --output HDMI-1 --off
	xrandr --output eDP-1 --auto --primary

	bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X

	# Terminate already running bar instances
	killall -q polybar
	
	# Wait until the processes have been shut down
	while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

	polybar laptop_only &
fi

nm-applet &

# https://www.reddit.com/r/bspwm/comments/c3bui3/change_focus_on_hover/
bspc config focus_follows_pointer true

#feh --bg-scale /usr/share/backgrounds/brad-huchteman-stone-mountain.jpg /usr/share/backgrounds/ryan-stone-skykomish-river.jpg
#feh --bg-scale /usr/share/backgrounds/ryan-stone-skykomish-river.jpg /usr/share/backgrounds/joshua-coleman-something-yellow.jpg
feh --bg-scale --randomize ~/.wallpaper/*

picom &
